;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/gw/demos/pod-line/" :create-asd-file? t)

(asdf:defsystem #:pod-line :description
 "The Gendl™ Suspended Pod Line Demo: rail in the neighbourhood, twin track cables between"
 :author "Genworks International" :license
 "Affero Gnu Public License (http://www.gnu.org/licenses/)" :serial t
 :version "20260929" :depends-on (:demos-common) :components
 ((:file "source/package") (:file "source/passage")
  (:gdl "source/track") (:gdl "source/pod")
  (:gdl "source/neighbourhood") (:gdl "source/cable")
  (:gdl "source/assembly") (:gdl "source/ui")
  (:file "source/publish")))
