;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/demos/lumber/" :create-asd-file? t)

(asdf:defsystem #:lumber :description
 "The Gendl™ lumber Subsystem" :author "Genworks International"
 :license "Affero Gnu Public License (http://www.gnu.org/licenses/)"
 :serial t :version "20260816" :depends-on nil :components
 ((:file "source/package") (:gdl "source/lumber")
  (:file "source/bom") (:file "source/solids-loader")))
