
stages:
  - update
  - build
  - fetch
  - deploy

update:
  stage: update
  script:
    - bash -x ./ci-script.sh linux git-pull

  
build:
  stage: build
#  when: manual
  script:
    - bash -x ./ci-script.sh linux load-script make-genworks-site


