;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/naca-nurbs/" :create-asd-file? t)

(asdf:defsystem #:naca-nurbs :description
 "The Gendl® naca-nurbs Subsystem" :author "Genworks International"
 :license "Affero Gnu Public License (http://www.gnu.org/licenses/)"
 :serial t :version "20260811" :depends-on (:demos-common) :components
 ((:file "source/nurbs") (:file "source/utilities")
  (:file "source/quality-reports-mixin") (:file "source/ui")
  (:file "source/publish")))
