;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/gw/demos/prompt-lab/" :create-asd-file? t)

(asdf:defsystem #:prompt-lab :description
 "The Gendl™ The Gendl™ Prompt lab: a visitor's prompt becomes a parametric Gendl model -- sessions, the modeling agent's tools, the agent loop, and the page with its viewer."
 :author "Genworks International" :license
 "Affero Gnu Public License (http://www.gnu.org/licenses/)" :serial t
 :version "20261005" :depends-on
 (:gwl-graphics :yason :alexandria :babel :demos-common :monocle)
 :components
 ((:file "source/package") (:file "source/parameters")
  (:file "source/session") (:file "source/archive")
  (:file "source/raster") (:file "source/tools")
  (:file "source/kinds") (:file "source/agent") (:file "source/docs")
  (:file "source/meter") (:file "source/guards")
  (:file "source/skins") (:file "source/app") (:file "source/page")
  (:file "source/browse") (:file "source/thumbs")
  (:file "source/export") (:file "source/uploads")
  (:file "source/project") (:file "source/review")
  (:file "source/hosting")
  (:file "source/routing") (:file "source/deploy")
  (:file "source/external")))
