;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/demos/staircase/" :create-asd-file? t)

(asdf:defsystem #:staircase :description
 "The Gendl™ staircase Subsystem" :author "Genworks International"
 :license "Affero Gnu Public License (http://www.gnu.org/licenses/)"
 :serial t :version "20260816" :depends-on (:demos-common :lumber)
 :components
 ((:file "source/package") (:gdl "source/assembly")
  (:gdl "source/ui") (:file "source/publish")))
