;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/gw/demos/demos-common/" :create-asd-file? t)

(asdf:defsystem #:demos-common :description
 "The Gendl™ demos-common Subsystem" :author "Genworks International"
 :license "Affero Gnu Public License (http://www.gnu.org/licenses/)"
 :serial t :version "20260911" :depends-on nil :components
 ((:file "source/cad-export") (:file "source/package")
  (:gdl "source/portal") (:file "source/source-strings")
  (:gdl "source/ui-mixin")))
