;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/demos/house/" :create-asd-file? t)

(asdf:defsystem #:house :description
 "The Gendl™ house Subsystem" :author "Genworks International"
 :license "Affero Gnu Public License (http://www.gnu.org/licenses/)"
 :serial t :version "20260816" :depends-on (:pui :deck) :components
 ((:file "source/package") (:gendl "source/assembly")
  (:gendl "source/brick-wall") (:file "source/initialize")
  (:gendl "source/ui")))
