;; Copyright © 2026 Gornskew Enterprises
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.  Distributed WITHOUT
;; ANY WARRANTY; see <https://www.gnu.org/licenses/agpl-3.0.html>.

;;;; The gear as numbers and sampled curves, no Gendl objects: ISO
;;;; 21771 names, the involute in closed form, the root fillet as the
;;;; trochoid generated by the rounded tip of the ISO 53 basic rack
;;;; rolling on the pitch circle, and the checks a drawing office
;;;; uses (tooth thickness at the pitch circle, the span measurement
;;;; over k teeth, contact ratio and working center distance of a
;;;; pair).  Everything here is checkable against a gear handbook;
;;;; profile.lisp turns the samples into NURBS.
;;;;
;;;; Frames.  The gear is centered at the origin; one tooth is
;;;; centered on the +x axis; angles are polar angles, positive
;;;; counter-clockwise, lengths in the module's unit.  The rack that
;;;; generates the fillet lives in its own frame: u along the pitch
;;;; line, y the depth below it toward the gear center; its tooth
;;;; (the cutter, which cuts the gear SPACE) is centered on u = 0.

(in-package :gear)

(defun deg->rad (degrees) (* (float degrees 1d0) (/ pi 180d0)))
(defun rad->deg (radians) (* radians (/ 180d0 pi)))

(defun involute-function (alpha)
  "inv(alpha) = tan alpha - alpha, the polar angle an involute has
unwound at pressure angle ALPHA (radians)."
  (- (tan alpha) alpha))

(defun undercut-shift-minimum (teeth pressure-angle &key (addendum 1d0))
  "The profile shift below which the rack tip undercuts the flank:
x_min = ha* - z sin^2(alpha) / 2."
  (let ((alpha (deg->rad pressure-angle)))
    (- addendum (/ (* teeth (expt (sin alpha) 2)) 2))))

(defun %rotate (x y phi)
  (values (- (* x (cos phi)) (* y (sin phi)))
          (+ (* x (sin phi)) (* y (cos phi)))))

(defun %roll (u y phi r)
  "The rack point (U, Y) -- U along the pitch line, Y the depth
toward the gear center -- in the gear frame after the rack has rolled
by PHI on the pitch circle of radius R."
  (%rotate (+ u (* r phi)) (- r y) phi))

(defun gear-numbers (&key (module 1d0) (teeth 20) (pressure-angle 20d0) (shift 0d0)
                          (addendum 1d0) (dedendum 1.25d0) (fillet 0.38d0) (backlash 0d0))
  "Every derived quantity of one spur gear, as a plist.  MODULE in mm
(or inches: nothing here cares), TEETH, PRESSURE-ANGLE in degrees,
SHIFT the profile shift coefficient x, ADDENDUM / DEDENDUM / FILLET the
basic-rack coefficients (ISO 53: 1, 1.25, 0.38), BACKLASH a tooth
thickness reduction in length units.  Signals when the gear would be
undercut (the fix is the :shift-minimum it names)."
  (let* ((m (float module 1d0))
         (z teeth)
         (alpha (deg->rad pressure-angle))
         (x (float shift 1d0))
         (r (/ (* m z) 2))
         (rb (* r (cos alpha)))
         (ra (+ r (* m (+ addendum x))))
         (rf (- r (* m (- dedendum x))))
         (rho (* fillet m))
         (s (- (* m (+ (/ pi 2) (* 2 x (tan alpha)))) backlash))
         (psi (/ s (* 2 r)))
         (pitch-angle (/ (* 2 pi) z))
         ;; the rack cutter: half space width at the pitch line, tip
         ;; depth, the tip-corner arc center and its tangent point on
         ;; the straight flank
         (e0 (- (* m pi 0.5d0) (/ s 2)))
         (yt (* m (- dedendum x)))
         (yc (- yt rho))
         (uc (- e0 (* yc (tan alpha)) (/ rho (cos alpha))))
         (ut (+ uc (* rho (cos alpha))))
         (ytt (+ yc (* rho (sin alpha))))
         ;; roll angles.  Rolling the rack by PHI about the gear puts
         ;; the rack point u = -r phi on the pitch circle at angle
         ;; pi/2 + phi, and a rack point (u, y) at
         ;; Rot(phi) . (u + r phi, r - y) in the gear frame (%roll).
         ;; The corner arc's bottom contacts the root circle when the
         ;; pitch point is straight above the arc center; the straight
         ;; flank takes over from the arc when its tangent point T
         ;; contacts, which is when the pitch point sits where T's
         ;; normal (the line of action) meets the pitch line.
         (phi-root (/ (- uc) r))
         (phi-form (/ (- (* ytt (/ (cos alpha) (sin alpha))) ut) r))
         (r-form (multiple-value-bind (px py) (%roll ut ytt phi-form r)
                   (sqrt (+ (* px px) (* py py)))))
         (shift-minimum (undercut-shift-minimum z pressure-angle :addendum addendum)))
    (when (or (< x (- shift-minimum 1d-9)) (<= r-form rb))
      (error "A ~a-tooth gear at ~a degrees is undercut at profile shift ~,3f; use shift >= ~,3f"
             z pressure-angle x shift-minimum))
    (when (< uc 0)
      (error "The rack tip fillet (~,3f) does not fit the tooth space at this shift; reduce :fillet" fillet))
    (flet ((theta (radius)
             ;; polar half-angle of the tooth at RADIUS, from the flank
             (- (+ psi (involute-function alpha))
                (involute-function (acos (/ rb radius))))))
      (let* ((theta-tip (theta ra))
             (theta-form (theta r-form))
             (k (max 2 (round (+ (* z (/ alpha pi)) 0.5d0))))
             (span (* m (cos alpha) (+ (* pi (- k 0.5d0)) (* z (involute-function alpha)) (* 2 x (tan alpha))))))
        (when (<= theta-tip 0)
          (error "The tooth comes to a point below the tip circle: reduce :shift or :addendum"))
        (list :module m :teeth z :pressure-angle (float pressure-angle 1d0) :shift x
              :addendum addendum :dedendum dedendum :fillet fillet :backlash backlash
              :pitch-radius r :base-radius rb :tip-radius ra :root-radius rf :form-radius r-form
              :pitch-diameter (* 2 r) :base-diameter (* 2 rb) :tip-diameter (* 2 ra) :root-diameter (* 2 rf)
              :tooth-thickness s :half-angle-pitch psi :pitch-angle pitch-angle
              :theta-tip theta-tip :theta-form theta-form
              :span-teeth k :span span
              :shift-minimum shift-minimum
              :rack (list :e0 e0 :yt yt :yc yc :uc uc :ut ut :yt-tangent ytt :rho rho
                          :phi-root phi-root :phi-form phi-form))))))

(defun pair-numbers (gear1 gear2)
  "A meshing pair: working pressure angle, working center distance,
contact ratio.  GEAR1 and GEAR2 are gear-numbers plists of the same
module and pressure angle."
  (let* ((m (getf gear1 :module))
         (alpha (deg->rad (getf gear1 :pressure-angle)))
         (z1 (getf gear1 :teeth)) (z2 (getf gear2 :teeth))
         (x1 (getf gear1 :shift)) (x2 (getf gear2 :shift))
         (inv-w (+ (involute-function alpha) (/ (* 2 (+ x1 x2) (tan alpha)) (+ z1 z2))))
         ;; invert the involute function by Newton on alpha_w
         (alpha-w (let ((a alpha))
                    (dotimes (i 60 a)
                      (let ((f (- (involute-function a) inv-w))
                            (df (- (/ 1 (expt (cos a) 2)) 1)))
                        (when (< (abs f) 1d-15) (return a))
                        (setq a (- a (/ f df)))))))
         (center (/ (* (+ z1 z2) m (cos alpha)) (* 2 (cos alpha-w))))
         (rb1 (getf gear1 :base-radius)) (rb2 (getf gear2 :base-radius))
         (ra1 (getf gear1 :tip-radius)) (ra2 (getf gear2 :tip-radius))
         (contact (/ (- (+ (sqrt (- (* ra1 ra1) (* rb1 rb1)))
                           (sqrt (- (* ra2 ra2) (* rb2 rb2))))
                        (* center (sin alpha-w)))
                     (* pi m (cos alpha)))))
    (list :working-pressure-angle (rad->deg alpha-w)
          :center-distance center
          :reference-center-distance (/ (* (+ z1 z2) m) 2)
          :contact-ratio contact
          :ratio (/ (float z2 1d0) z1))))

;;; --- sampled curves ---------------------------------------------------

(defun %involute-samples (numbers side n)
  "N points along one flank from the form radius to the tip, as
(x y) in the gear frame, in counter-clockwise order.  SIDE :upper is
the +angle flank of the tooth on the +x axis (ordered tip -> form),
:lower the -angle flank (ordered form -> tip)."
  (let* ((rb (getf numbers :base-radius))
         (r-form (getf numbers :form-radius))
         (ra (getf numbers :tip-radius))
         (psi (getf numbers :half-angle-pitch))
         (alpha (deg->rad (getf numbers :pressure-angle)))
         (beta (+ psi (involute-function alpha)))
         ;; sample uniformly in the roll angle, which spreads points
         ;; where the curvature is
         (t-form (sqrt (- (expt (/ r-form rb) 2) 1)))
         (t-tip (sqrt (- (expt (/ ra rb) 2) 1)))
         (points
           (loop for i from 0 to (1- n)
                 for tt = (+ t-form (* (- t-tip t-form) (/ i (float (1- n) 1d0))))
                 for radius = (* rb (sqrt (+ 1 (* tt tt))))
                 for angle = (- beta (involute-function (atan tt)))
                 collect (list (* radius (cos angle)) (* radius (sin angle))))))
    (ecase side
      (:upper (nreverse points))
      (:lower (mapcar (lambda (p) (list (first p) (- (second p)))) points)))))

(defun %fillet-samples (numbers side n)
  "N points along the root fillet the rack tip generates, from the
root circle to the form radius, as (x y) in the gear frame.  SIDE as
in %involute-samples: :upper is ordered form -> root (counter-
clockwise on the tooth's +angle side), :lower root -> form."
  (let* ((r (getf numbers :pitch-radius))
         (rack (getf numbers :rack))
         (uc (getf rack :uc)) (yc (getf rack :yc)) (rho (getf rack :rho))
         (phi-root (getf rack :phi-root)) (phi-form (getf rack :phi-form))
         (half-pitch (/ (getf numbers :pitch-angle) 2))
         (points
           (loop for i from 0 to (1- n)
                 for phi = (+ phi-root (* (- phi-form phi-root) (/ i (float (1- n) 1d0))))
                 collect
                 (multiple-value-bind (cx cy) (%roll uc yc phi r)
                   (multiple-value-bind (ix iy) (%rotate 0d0 r phi)
                     (let* ((dx (- ix cx)) (dy (- iy cy))
                            (len (sqrt (+ (* dx dx) (* dy dy))))
                            (ex (- cx (* rho (/ dx len))))
                            (ey (- cy (* rho (/ dy len))))
                            (radius (sqrt (+ (* ex ex) (* ey ey))))
                            ;; offset from the space center, which the
                            ;; rack frame puts on the +y axis
                            (delta (abs (- (atan ey ex) (/ pi 2))))
                            (angle (- half-pitch delta)))
                       (list (* radius (cos angle)) (* radius (sin angle)))))))))
    (ecase side
      (:upper (nreverse points))
      (:lower (mapcar (lambda (p) (list (first p) (- (second p)))) points)))))

(defun gear-profile-segments (numbers &key (involute-points 24) (fillet-points 12))
  "One tooth period of the closed profile, counter-clockwise, as a
list of segment plists: (:kind :points :points ((x y) ...)) for the
sampled fillets and flanks, (:kind :arc :radius R :start A :end B)
for the tip land and the root land.  Starts where the previous
tooth's root land ends; rotate by k * :pitch-angle for tooth k."
  (let* ((ra (getf numbers :tip-radius))
         (rf (getf numbers :root-radius))
         (theta-tip (getf numbers :theta-tip))
         (half-pitch (/ (getf numbers :pitch-angle) 2))
         (delta-root (abs (getf (getf numbers :rack) :phi-root))))
    (list (list :kind :points :name :lower-fillet
                :points (%fillet-samples numbers :lower fillet-points))
          (list :kind :points :name :lower-flank
                :points (%involute-samples numbers :lower involute-points))
          (list :kind :arc :name :tip-land :radius ra :start (- theta-tip) :end theta-tip)
          (list :kind :points :name :upper-flank
                :points (%involute-samples numbers :upper involute-points))
          (list :kind :points :name :upper-fillet
                :points (%fillet-samples numbers :upper fillet-points))
          (list :kind :arc :name :root-land :radius rf
                :start (- half-pitch delta-root) :end (+ half-pitch delta-root)))))

(defun gear-report (numbers &optional pair)
  "The numbers a drawing needs, as an alist of name -> value with
lengths rounded to 4 places."
  (flet ((r4 (v) (coerce (/ (round (* v 10000)) 10000) 'single-float)))
    (append
     `(("module" . ,(getf numbers :module))
       ("teeth" . ,(getf numbers :teeth))
       ("pressure_angle_deg" . ,(getf numbers :pressure-angle))
       ("profile_shift" . ,(getf numbers :shift))
       ("pitch_diameter" . ,(r4 (getf numbers :pitch-diameter)))
       ("base_diameter" . ,(r4 (getf numbers :base-diameter)))
       ("tip_diameter" . ,(r4 (getf numbers :tip-diameter)))
       ("root_diameter" . ,(r4 (getf numbers :root-diameter)))
       ("form_diameter" . ,(r4 (* 2 (getf numbers :form-radius))))
       ("tooth_thickness_at_pitch" . ,(r4 (getf numbers :tooth-thickness)))
       ("span_teeth" . ,(getf numbers :span-teeth))
       ("span_measurement" . ,(r4 (getf numbers :span)))
       ("undercut_shift_minimum" . ,(r4 (getf numbers :shift-minimum))))
     (when pair
       `(("mate_teeth" . ,(getf pair :mate-teeth))
         ("ratio" . ,(r4 (getf pair :ratio)))
         ("working_pressure_angle_deg" . ,(r4 (getf pair :working-pressure-angle)))
         ("center_distance" . ,(r4 (getf pair :center-distance)))
         ("contact_ratio" . ,(r4 (getf pair :contact-ratio))))))))
