;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/gw/demos/prompt-lab/prompt-lab-sheet/" :create-asd-file? t)

(asdf:defsystem #:prompt-lab-sheet :description
 "The Gendl™ The Prompt lab as one gwl sheet: the page's sections pushed to the browser over a stream as the agent works, Datastar as the client."
 :author "Genworks International" :license
 "Affero Gnu Public License (http://www.gnu.org/licenses/)" :serial t
 :version "20261001" :depends-on (:prompt-lab) :components
 ((:file "source/sheet")))
