;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/demos/deck/" :create-asd-file? t)

(asdf:defsystem #:deck :description
 "The Gendl™ deck Subsystem" :author "Genworks International"
 :license "Affero Gnu Public License (http://www.gnu.org/licenses/)"
 :serial t :version "20260816" :depends-on (:pui :bench) :components
 ((:file "source/package") (:file "source/assembly")
  (:gendl "source/ui")))
