;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/gw/demos/gear/" :create-asd-file? t)

(asdf:defsystem #:gear :description
 "The Gendl™ gear Subsystem" :author "Genworks International"
 :license "Affero Gnu Public License (http://www.gnu.org/licenses/)"
 :serial t :version "20260911" :depends-on (:demos-common)
 :components
 ((:file "source/package") (:file "source/geometry")
  (:file "source/profile") (:file "source/publish")))
