;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/demos/gorg/" :create-asd-file? t)

(asdf:defsystem #:gorg :description
 "The Gendl™ gorg Subsystem" :author "Xinyue (Cherie) Yang" :license
 "Affero Gnu Public License (http://www.gnu.org/licenses/)" :serial t
 :version "20260816" :depends-on (:html-template :gwl-graphics)
 :components
 ((:file "source/package") (:file "source/base-framework")
  (:file "source/publish")))
