;;;; -*- coding: utf-8 -*-

;;; Do not edit; generated by (cl-lite "/projects/demos/x3dom-page/" :create-asd-file? t)

(asdf:defsystem #:x3dom-page :description
 "The Gendl™ x3dom-page Subsystem" :author "Genworks International"
 :license "Affero Gnu Public License (http://www.gnu.org/licenses/)"
 :serial t :version "20260816" :depends-on nil :components
 ((:gdl "source/x3dom-page")))
